config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :users, only: [:index, :show, :create]
  resources :posts, only: [:index, :show, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  match '/users/:id/finish_signup' => 'users#finish_signup',  via: [:get, :patch], as: :finish_signup
  match '/users/:id/combine_profiles' => 'users#combine_profiles', via: [:post, :get, :patch], as: :combine_profiles
  match '/users/:id/merge_profiles' => 'users#merge_profiles', via: [:get, :patch], as: :merge_profiles
  match '/users/:id/add_avatar' => 'users#add_avatar', via: [:get, :post], as: :add_avatar

  match '/rating' => 'posts#image_rating', via: :get, as: :image_rating
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "100x100#", :small => "50x50#" }
  has_many :identity
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :username, presence: true, length: { minimum: 3, maximum: 50 }
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpg|jpeg|png)$/, :message => 'file type is not allowed (only jpeg/png images)'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  TEMP_EMAIL_REGEX = /not@verified.com/

  def self.from_omniauth(auth, signed_in_resources = nil)

    identity = Identity.find_for_oauth(auth)
    user = signed_in_resources ? signed_in_resources : identity.user

    if user.nil?
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(username: auth.info.name,
                        email: email ? email : "#{auth.uid}-not@verified.com",
                        password: "foobar")
        user.save
      end
    end

    unless identity.user == user
      identity.user = user
      identity.save
    end

    user

  end

  def email_verified?
    self.email !~ TEMP_EMAIL_REGEX
  end

  def migrate
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def self.providers_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, :event => :authentication
          set_flash_message(:notice, :success, :kind => "#{provider}") if is_navigational_format?
        else
          session["devise.#{provider}_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end      
    }
  end

  [:facebook, :vkontakte, :twitter, :instagram].each do |provider|
    providers_callback_for provider
  end

  def after_sign_in_path_for(resources)
    if resources.email_verified?
      super resources
    else
      finish_signup_path(resources)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    if signed_in? 
      @post = current_user.posts.build
    end
  end
 
  def index
    @users = User.paginate(page: params[:page])
  end

  def add_avatar
    if request.post? && params['user']
      current_user.update_attributes(avatar: params['user']['avatar'])
    else
      flash.now[:warning] = "Загрузите изображение" if request.post? 
    end
  end

  def finish_signup
    flash.now[:notice] = "Укажите свой email (он будет использоваться для входа в систему)"
 
    if request.patch?
      if current_user.update_attributes(email: params['user']['email'])
        redirect_to current_user
        flash[:notice] = "Ваш почтовый адрес '#{params['user']['email']}'' успешно обновлен"
      end
    end
  end

  def combine_profiles
    unless params['user']['email'].empty?
      @user = User.find_by(email: params['user']['email'])
      if @user.valid_password?(params['user']['password'])
        ident = Identity.find_by(user_id: params[:id])
        
        if params['user']['migrate'] == '1'
          @user.update_attributes(username: current_user.username)       
        end

        ident.update_attributes(user_id: @user.id)
        social_profile_destroy
        redirect_to current_user
      end
    end
  end

  def merge_profiles
    @all_social_profiles = ["vkontakte", "twitter", "instagram", "facebook"]
    @social_profiles = current_user.identity
  end

  private

    def social_profile_destroy
      user_delete_id = current_user.id
      current_user.destroy
      sign_in @user
    end

end

app/views/users/add_avatar.html.erb
<%= render('layouts/aside_menu') %>
<div class="col-md-6">
  <h3>Изменить изображение аватара</h3>
  <div class="col-md-3 col-md-offset-1">
    <% unless current_user.avatar_file_name.nil? %>
        <li class="img-thumbnail"><%= image_tag(current_user.avatar.url(:medium)) %></li>
    <% else %>
      <li class="img-thumbnail"><%= image_tag("missing.jpg") %></li>
    <% end %>
  </div>
  <div class="col-md-8">
    <%= form_for(:user, controller: 'users', action: 'combine_profiles', html: { multipart: true }) do |f| %>
      <%= f.file_field :avatar %>
      <%= f.submit "Изменить фотографию", class: "btn btn-sm btn-success margin-top-fix" %>
    <% end %>
  </div>
</div>

app/views/users/combine_profiles.html.erb
<% provide(:title, 'Combine') %>

<div class="row center">
  <h1>Привязать к профилю</h1>
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(:user, controller: 'users', action: 'combine_profiles', url: combine_profiles_path, method: 'patch', html: { class: "form-horizontal margin-top-fix" }) do |f| %>
      <fieldset>
        <div class="form-group">
            <%= f.label :email, class: "col-md-2 control-label" %>
            <div class="col-md-10">
              <%= f.email_field :email, autofocus: true, value: "", placeholder: "Ваш email", class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label "Пароль", class: "col-md-2 control-label" %>
            <div class="col-md-10">
              <%= f.password_field :password, autocomplete: 'off', placeholder: "Ваш пароль", class: "form-control" %>
            </div>
        </div>        
      <%= f.submit "Привязать профиль", class: "btn btn-success" %>
      <%= f.check_box :migrate %>
      <%= f.label :migrate, "Импортировать ваши данные" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <%= form_for(current_user, as: 'user', url: finish_signup_path(current_user), html: { role: 'form'}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, autofocus: true, value: '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Укажите свой почтовый адрес.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Продолжить', class: 'btn btn-success' %>
      <%= f.button 'Интегрировать с уже существующим', class: 'btn btn-primary', formaction: combine_profiles_path %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Все пользователи') %>
<h1>Все пользователи</h1>

<%= will_paginate %>

<div class="row">
  <ul class="users">
    <% @users.each do |user| %>
      <div class="col-md-3">
        <li>
        <% unless user.avatar_file_name.nil? %>
          <%= image_tag(user.avatar.url(:small), class: "img-thumbnail") %>
        <% else %>
          <%= image_tag("missing.jpg", class: "img-thumbnail missing") %>
        <% end %>
          <%= link_to user.username, user %>
        </li>
      </div>
    <% end %>
  </ul>
</div>

<%= will_paginate %>

app/views/users/merge_profiles.html.erb
<% provide(:title, "Объединить профили") %>
<%= render('layouts/aside_menu') %>
<div class="col-md-6">
  <h3>Объединить профили</h3>
  <p>Вы можете объединить свои профили социальных сетей в один аккаунт.</p>
  <p>Добавленные профили:</p>
    <ul>
      <% if @social_profiles %>
        <% @social_profiles.each do |profile| %>
          <li class="text-success"><%= profile.provider %></li>
          <% @all_social_profiles.delete(profile.provider) %>
        <% end %>
      <% else %>
        <li>
          <i>Вы не интегрировали ни одного профиля.</i>
        </li>
    <% end %>
  </ul>
  
  <% unless @all_social_profiles.empty? %>
    <p>Вы можете интегрировать профили:</p>
    <ul>
      <% @all_social_profiles.each do |profile| %>
        <li><%= link_to profile, user_omniauth_authorize_path(profile) %></li>
      <% end %>
    </ul>
  <% end %>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<div class="row user-header">
  <div class="col-md-2">
  <% unless @user.avatar_file_name.nil? %>
      <li class="img-thumbnail"><%= image_tag(@user.avatar.url(:medium)) %></li>
    <% else %>
      <li class="img-thumbnail"><%= image_tag("missing.jpg") %></li>
  <% end %>   
  </div>
  <div class="col-md-7">
    <h1>
      <%= @user.username %>
    </h1>
    <p>
      <%= @user.email %>
    </p>
  </div>
  <div class="col-md-3">
    <div class="btn-group stat-group">
      <%= link_to "Добавить фото", posts_path, class: "btn btn-success" %>
      <span href="#" class="btn btn-default"><%= @user.posts.count %> фото</span>
    </div>
  </div>
</div>

<% if @user.posts.any? %>
  <div class="row content-wrapper-posts">
    <% @user.posts.order("created_at DESC").each do |user_post| %>
      <div class="col-md-3">
        <div class="post-bg center">
          <div class="post-date">
               <%= user_post.created_at.strftime("%d %b. %Y %H:%M") %>
          </div>
          <%= link_to image_tag(user_post.image.url(:small)), post_path(user_post.id.to_s) %> 
          <div class="post-info">
            <span class="post-info-likes">
              <span class="glyphicon glyphicon-heart"></span>
              <%= user_post.likes.count %>
            </span>
            <span class="post-info-comments">
              <span class="glyphicon glyphicon-comment"></span>
              <%= user_post.comments.count %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @posts %>
<% end %>