config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :users, only: [:index, :show, :create]
  resources :posts, only: [:index, :show, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  match '/users/:id/finish_signup' => 'users#finish_signup',  via: [:get, :patch], as: :finish_signup
  match '/users/:id/combine_profiles' => 'users#combine_profiles', via: [:post, :get, :patch], as: :combine_profiles
  match '/users/:id/merge_profiles' => 'users#merge_profiles', via: [:get, :patch], as: :merge_profiles
  match '/users/:id/add_avatar' => 'users#add_avatar', via: [:get, :post], as: :add_avatar

  match '/rating' => 'posts#image_rating', via: :get, as: :image_rating
end

app/views/layouts/_aside_menu.html.erb
<div class="col-md-3">
  <h2>Настройки</h2>
  <ul class="nav nav-pills nav-stacked">
    <%= nav_link "Редактировать профиль", edit_user_registration_path %>
    <%= nav_link "Изображение аватара", add_avatar_path(current_user.id) %>
    <%= nav_link "Объединить профили", merge_profiles_path(current_user.id) %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    <%= link_to "Foodgram", root_path %> by Alexandr Goncurin
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "О нас", '#' %>
      </li>
      <li>
        <%= link_to "Контакты", '#' %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Foodgram",root_path, class: "navbar-brand" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li>
            <%= link_to "Главная", root_path %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to "Пользователи", users_path %>
            </li>
            <li>
              <%= link_to "Самое популярное", image_rating_path %>
            <li class="fat-menu dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.username %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Профиль", current_user %>
                </li>
                <li>
                  <%= link_to "Настройки", edit_user_registration_path %>
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to "Выход", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>  
            <li>
              <%= link_to "Войти", user_session_path %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'united', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render("layouts/header") %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render("layouts/footer") %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>